name: cwtch
description: Metadata Resistant Chat

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.10.0+36

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.3
  package_info_plus: ^1.0.0
  #intl_translation: any
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  ffi: ^1.2.1
  path_provider: ^2.0.0
  crypto: ^3.0.2

  glob: any
  scrollable_positioned_list: ^0.3.2
  file_picker: ^4.3.2
  file_picker_desktop: ^1.1.1
  url_launcher: ^6.0.18
  window_manager: ^0.2.8
  # notification plugins
  win_toast: ^0.0.2
  flutter_local_notifications: ^9.6.1
  desktop_notifications: ^0.6.3
  qr_flutter: ^4.0.0

dev_dependencies:
  msix: ^3.6.2
  build_runner: any
  flutter_gherkin:
    #path: ./flutter_gherkin
    git:
      url: https://git.openprivacy.ca/openprivacy/flutter_gherkin
      ref: main

# Uncomment to update lokalise translations (see README for list of deps to comment out bc incompatibilities)
#dev_dependencies:
#  flutter_lokalise: any
#flutter_lokalise:
#  project_id: "737094205fceda35c50aa2.60364948"
#  api_token: "0407300fe4aa1edf1c1818e56234589e74c83c59" # Read only api Token from Dan


flutter_intl:
  enabled: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # makes flutter build/run generate app_localizations.dart (per l10n.yaml)
  generate: true

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  assets:
    - assets/
    - assets/core/
    - assets/profiles/
    - assets/servers/

  fonts:
    - family:  Cwtch
      fonts:
        - asset: assets/fonts/Cwtch.ttf
    - family: RobotoMono
      fonts:
          - asset: assets/fonts/RobotoMono-Regular.ttf
          - asset: assets/fonts/RobotoMono-Bold.ttf
            weight: 700

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages


msix_config:
  display_name: Cwtch
  publisher_display_name: Open Privacy Research Society
  identity_name: im.cwtch.flwtch
  msix_version: 1.0.0.0
  certificate_path: codesign.pfx
  certificate_password: pfx_pass
  publisher: CN=Open Privacy Research Society, O=Open Privacy Research Society, L=Vancouver, S=British Columbia, C=CA
  logo_path: cwtch.png
  start_menu_icon_path: cwtch.png
  tile_icon_path: assets\cwtch_title.png
  icons_background_color: transparent
  architecture: x64
  capabilities: 'internetClient'
